# site settings
title: "TheGermanTruth"
meta_title: "Kritische Analysen & Essays | The German Truth"
subtitle: "2026 by Klaus Runge"
email: "runge.post@outlook.de"
description: "Unabhängige Analysen und kritische Essays zu Politik, Gesellschaft und globalen Dynamiken. Fundierte Hintergründe für Deutschland. Jetzt lesen!"


theme: null
markdown: kramdown


plugins:
  - jekyll-sitemap

url: "https://thegermantruth.github.io"
baseurl: ""






